### ISSUE TITLE
Add HD Icons

### ISSUE THREAD

**Issue by NovaGL** [matthuisman/plugin.video.au.freeview#1]
Hi,

I noticed you don't have HD icons not sure if it is relevant as the IPTV stream might only be HD?

Also some icons are black making them hard to see.

ABC HD
![ABCHD](https://i.imgur.com/81o805I.png)

SBS HD
![SBSHD](https://i.imgur.com/DXk5cvP.png)

7HD
![7HD](https://upload.wikimedia.org/wikipedia/en/thumb/9/99/7HD_2016_Logo.svg/1200px-7HD_2016_Logo.svg.png)

9HD
![9HD](https://upload.wikimedia.org/wikipedia/en/7/7f/Nine_HD_logo_2015.png)

10HD can't see the HD as it's in white
![10HD](https://i.imgur.com/dpjLpht.png)

---

Outdoor Channel in white
![Outdoor Channel](https://i.imgur.com/FRicFZB.png)

**Comment by matthuisman** [comment]
Your using the default kodi skin?

**Comment by NovaGL** [comment]
No. Do they all appear correct for you?

**Comment by matthuisman** [comment]
The default skin is quite dark.
So light icons show fine.

Ideally, all icons should be like below so background doesn't matter.
![redbulltv](https://user-images.githubusercontent.com/6225961/62343534-2b90fc80-b53f-11e9-8d7b-2f9196fb3fbc.jpg)

**Comment by NovaGL** [comment]
The outdoor one has black text in your version

**Comment by matthuisman** [comment]
It has a slim white outline so still slightly visible.
I'll look into changing it.

If you use my IPTV Merge add-on, you can also change logos :)

**Comment by NovaGL** [comment]
I know I can change things but that doesn't help others

**Comment by matthuisman** [comment]
I have updated the Outdoor icon to your one.
The rest of the channels get their logo from freeview epg data.
So a pain currently to change manually.
IPTV 2.0 I'll look into better icons.
