### ISSUE TITLE
(Request) Option to turn off channels

### ISSUE THREAD

**Issue by brentonv** [matthuisman/plugin.video.au.freeview#2]
Hi Matt. Thanks for sharing this great add-on it's very neat and works great.

I just have a small request please would it be possible to add an option to disable unwanted channels?

Thanks matey!

**Comment by matthuisman** [comment]
you can use my IPTV Merge to get the channels into Kodi's TV menu (and then you get full guide as well). You can then use IPTV Merge to hide channels :)

**Comment by brentonv** [comment]
Just tested it. Holy crap. This just blew my mind you are freaking amazing. Thanks mate
